# Generation parameters to give the transformers.TextGenerationPipeline
generation_params:
  return_full_text: False
  max_new_tokens: 4096
  handle_long_generation: "hole"

# The parameters to establish the connection to the server
connection_params:
  host: "172.16.222.12"
  port: 9300
  endpoint_name: "chat_completion"
